### ISSUE TITLE
Move linux-64/fipy-3.3-py27h5ca1d4c_0.tar.bz2 from ``main`` to ``broken``

### ISSUE THREAD

**Issue by guyer** [conda-forge/fipy-feedstock#9]
Hi @conda-forge/core,

Please move my build  linux-64/fipy-3.3-py27h5ca1d4c_0.tar.bz2 from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

Build 0 is being loaded preferentially to build 1.

**Comment by guyer** [comment]
Please also move `osx-64/fipy-3.3-py27h5ca1d4c_0.tar.bz2` from `main` to `broken`

**Comment by ocefpaf** [comment]
Done. Please check: https://anaconda.org/conda-forge/fipy/files?channel=broken
